<?xml version="1.0" encoding="utf-8"?>

<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/niklaslundberg/Arbor.Hypermedia</PackageProjectUrl>
    <RepositoryUrl>https://github.com/niklaslundberg/Arbor.Hypermedia</RepositoryUrl>
    <Authors>Niklas Lundberg</Authors>
  </PropertyGroup>
</Project>