<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="HyperMediaLayout.cshtml" />
    <None Remove="HyperMediaView.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Views\Shared\HyperMediaLayout.cshtml" />
    <EmbeddedResource Include="Views\Shared\HyperMediaView.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Arbor.AppModel" />
    <PackageReference Include="Arbor.ModelBinding.Primitives" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" />
  </ItemGroup>

</Project>
